version: "3"

services:
  api:
    image: nanmu42/qrcode-api
    command: ./qrcode-api -config ./configs/api.toml
    hostname: api
    ports:
    - 3100:3100
    expose:
    - "3100"
    volumes:
    - ./configs:/qrcode/configs
    - ./logs:/qrcode/logs
    stop_grace_period: 30s
    restart: unless-stopped